//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string TimeOfMeeting { get; set; }
        public string TitleOfMeeting { get; set; }
        public Nullable<System.DateTime> create { get; set; }
        public string Channel { get; set; }
    }
}
